## Numpy
It is the fundamental library which provides you the support of array , matrices along with collection of mathematical functions to operate with the data, focusing on array and vectorised operation

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])   # a single linear array has been created 
print(arr)  # it is an arr not a list (numpy array)
print(type(arr))  # nd array 
print(arr.shape)  # it is a single dimension array with 5 elements 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   # converting the 1D array into the 2D array , 1 row and 5 cols 
# by this you can probably convert the shape and size of the matrix


array([[1, 2, 3, 4, 5]])

In [ ]:
arr3 = np.array([[1,2,3]])
arr3.shape  # 1 row and 3 cols so the shape is (1,3)

(1, 3)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape
print(arr)
print(arr.shape)  # 2 rows and 3 cols 

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
np.arange(0,10,2)  # it gives the array form 0 to 10 with the difference of 2


array([0, 2, 4, 6, 8])

In [5]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(3)  # identity matrix of size 3X3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise addition
print("Addition : ", arr1 + arr2)

# Element wise subtraction
print("Subtraction : ", arr2-arr1)

# Element wise multiplication
print("Multiplication : ", arr1*arr2)

# Element wise Division
print("Divison : ", arr1/arr2)


Addition :  [11 22 33 44 55]
Subtraction :  [ 9 18 27 36 45]
Multiplication :  [ 10  40  90 160 250]
Divison :  [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# Universal functions in numpy
import numpy as np
arr = np.array([1,2,3,4,5])

# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# Indexing and Slicing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0][0])  # 0 based indexing
print(arr[2][2])
print(arr[1:]) # from the 1st indexed row to all the rem rows
print(arr[1:,2:]) # select the rows from the 1th to rem all and then go for the 2nd indexed colums value to rem all 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
[[4 5 6]
 [7 8 9]]
[[6]
 [9]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2]) # select the rows from the 0th to 2nd (last index will be ignored)

[[1 2 3]
 [4 5 6]]


In [ ]:
# modify array element (both below are same just different methods to show )
arr[0,0] = 100
arr[0][0] = 100 


NOTE :- This numpy module is used in various statistical and data related concepts and used to normalized the data since it also has some statistical functions

In [ ]:
# statistical concepts -> Normalized data
# to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# calculate the mean and the standard deviations
mean = np.mean(data)
std_dev = np.std(data)

# variance
vairance = np.var(data)

# Normalized the data
normalized_data = (data-mean)/std_dev  # this is the normalized data
print("Normalized Data : ",normalized_data)

Normalized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [22]:
# logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data > 5)
print(data[data > 5])
print(data[(data >= 5) & (data <=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
